---
  - name: Install dependancies
    apt: name={{ item.name }} update-cache=yes cache_valid_time=3600
    with_items: apt_packages

  - name: Ensure correct package is installed and updated
    apt: deb=https://dl.ubnt.com/firmwares/unifi-video/3.1.5/unifi-video_3.1.5~Debian7_amd64.deb

  - name: Ensure service is started
    service: name=unifi-video state=started
