---

  - name: Install nginx
    apt: name=nginx update-cache=yes cache_valid_time=3600 force=yes

# Need to add a file check before this stage

  - name: Remove defaults
    command: unlink /etc/nginx/sites-enabled/default

  - name: Test nginx Config
    command: nginx -t

  - name: Restart nginx
    service: name=nginx state=restart
#/etc/nginx/sites-available/newservice /etc/nginx/sites-enabled/
